import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import csv
from astropy.io import fits
import os.path
from pathlib import Path

## Read in DR14 catalog generated by APOGEE_ID.py
filename = 'DR14_Catalog_Stats.csv'
data_dr14 = pd.read_csv(filename)
# Read in columns of data we want for the function "matches"
locationid = data_dr14['LocationID']
apogeeid = data_dr14['ApogeeID']
visits = np.asarray(data_dr14['Visit'])
snr = np.asarray(data_dr14['SNR'])
R51 = np.asarray(data_dr14['log(R51)'])
R101 = np.asarray(data_dr14['log(R101)'])
R151 = np.asarray(data_dr14['log(R151)'])
xranges = np.asarray(data_dr14['log(xr)'])
ratio1 = np.asarray(data_dr14['log(Ratio1)'])
ratio2 = np.asarray(data_dr14['log(Ratio2)'])
peak_value = np.asarray(data_dr14['Peak_value'])

match_param_array = []
match_apogeeid = []
match_locationid = []
uniqueID = np.unique(apogeeid)
for i in range(len(uniqueID)):
    print(i)
    newID = np.where(apogeeid == uniqueID[i])
    new_array = newID[0]
    new_param_array = xranges[new_array]
    new_apo = apogeeid[new_array]
    small_val = max(new_param_array)
    print(small_val)
    if small_val != 'nan':
        loc_small_val = np.where(new_param_array == small_val)
        small_loc = loc_small_val[0][0]
        small_param = round(small_val,4)
        #array for small parameters
        match_param_array.append(small_param)
        #array for matching apogee ids and location ids
    else:
        match_apogeeid.append(apogeeid[i])
        match_locationid.append(locationid[i])


# loc_id = []
# apo_id = []
# for i in range(len(xranges)):
#     if xranges[i] == '':
#         print(i)
#         loc_id.append(locationid[i])
#         apo_id.append(apogeeid[i])

# cols = ['Location_ID','Apogee_ID']
# df = pd.DataFrame(columns=cols)
# df['Location_ID'] = match_apogeeid
# df['Apogee_ID'] = match_locationid
# df.to_csv('Conflicting_Targets.csv')